# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.supportedFilesystems = [ "btrfs" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2aaf11ed-36ea-4a05-bc96-0f0511f28278";
      fsType = "btrfs";
      options = [ "noatime" "discard" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/ef39502a-c34f-4bc6-a5ed-00ed84eefc66";

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
}
